#!/bin/sh
# Copies the banner card renderer the site uses (assets/banner.css and
# assets/banner.js) into backend/BannerView.html, which the admin modal
# includes, so the modal's preview draws cards exactly like the event iPad.
# Run it after changing either file, before `clasp push`.
cd "$(dirname "$0")/.." || exit 1
{
  echo '<!-- Generated by tools/build-banner-view.sh from assets/banner.css and assets/banner.js. Edit those, then rerun it. -->'
  echo '<style>'
  cat assets/banner.css
  echo '</style>'
  echo '<script>'
  cat assets/banner.js
  echo '</script>'
} > backend/BannerView.html
